module.exports = [
  './gulp/tasks/sass',
  './gulp/tasks/html',
  './gulp/tasks/css',
  './gulp/tasks/js',
  './gulp/tasks/scripts',
  './gulp/tasks/allimg',
  './gulp/tasks/webp',
  './gulp/tasks/images',
  './gulp/tasks/svg',
  './gulp/tasks/serve',
  './gulp/tasks/copy',
  './gulp/tasks/clean',
  './gulp/tasks/build',
];